package com.imagosur.domain;

public enum TipoEvaluacion {
    AUTOEVALUACION, EN_CONJUNTO, SOLO_POTENCIAL,
    AUTOEVALUACION_JERARQUICO, EN_CONJUNTO_JERARQUICO, SOLO_POTENCIAL_JERARQUICO,
    AUTOEVALUACION_JERARQUICO_BSF, EN_CONJUNTO_JERARQUICO_BSF, SOLO_POTENCIAL_JERARQUICO_BSF,
    AUTOEVALUACION_CORPORATIVO, EN_CONJUNTO_CORPORATIVO, SOLO_POTENCIAL_CORPORATIVO;

}
